language: cpp

compiler:
  - g++

before_install:
  - sudo pip install cpp-coveralls
<<<<<<< HEAD
  - sudo apt-get install libboost1.48-all-dev 
  - sudo apt-get install libssl-dev
  - sudo apt-get install cmake
  - sudo apt-get install libxml++2.6-dev
  - sudo apt-get install uuid-dev
  - sudo apt-get install libunittest++-dev
=======
  - sudo apt-get install libssl-dev cmake libxml++2.6-dev uuid-dev libunittest++-dev 
  - sudo apt-get install libboost1.54-all-dev # Travis run with Ubuntu 12.04 which doesn't have 1.54 yet so this will fail
>>>>>>> aafbf5067dadc3062a99b52e7cfc360814486575

script:
  - ./configure.sh && cd Microsoft.WindowsAzure.Storage/build.release && make

# after_success:
#   - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
