language: cpp

compiler:
  - g++

before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-cache search libboost
  - sudo apt-get install libboost-all-dev 
  - sudo apt-get install libssl-dev
  - sudo apt-get install cmake
  - sudo apt-get install libxml++2.6-dev
  - sudo apt-get install uuid-dev
  - sudo apt-get install libunittest++-dev

script:
  - ./configure.sh && cd Microsoft.WindowsAzure.Storage/build.release && make

# after_success:
#   - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
