language: cpp

compiler:
  - g++

before_install:
  - sudo pip install cpp-coveralls

script:
  - ./configure.sh && cd Microsoft.WindowsAzure.Storage/build.release && make

# after_success:
#   - coveralls --exclude lib --exclude tests --gcov-options '\-lp'