language: cpp

compiler:
  - g++

before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-get install libboost1.54-dev libssl-dev cmake libxml++2.6-dev uuid-dev libunittest++-dev

script:
  - ./configure.sh && cd Microsoft.WindowsAzure.Storage/build.release && make

# after_success:
#   - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
